# Full path of where to store log file ('default' will translate to same dir as script)
log_output_path: default

#List of source folders to check for files
folders_to_check:
  test_folder1: "/home/user/test_dir1"
  test_folder2: "/home/user/test_dir2"

#List of tags to check
tags_to_sort:
# Example tags: tags are listed without brackets: followed by destination path
  test1: "/home/user/destination_dir1/"
  test2: "/home/user/destination_dir2/"
  test3: "/home/user/destination_dir3/"

